spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    # Enable batch inserts
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
