grpc:
  client:
    product:
      address: ${GRPC_CLIENT_PRODUCT_ADDRESS:'static://127.0.0.1:50052'}
      enableKeepAlive: 'true'
      keepAliveWithoutCalls: 'true'
      negotiationType: plaintext
    user:
      enableKeepAlive: 'true'
      negotiationType: plaintext
      keepAliveWithoutCalls: 'true'
      address: ${GRPC_CLIENT_USER_ADDRESS:'static://127.0.0.1:50051'}
