spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  event:
    publisher:
      kafka:
        topics:
          user_events: user_events
          product_events: product_events
          order_events: order_events
