spring:
  quartz:
    properties:
      org:
        quartz:
          dataSource:
            quartz:
              driver: com.mysql.cj.jdbc.Driver
              URL: ${MYSQL_QUARTZ_URL:jdbc:mysql://localhost:3306/db_user?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
              user: ${MYSQL_QUARTZ_USERNAME:root}
              password: ${MYSQL_QUARTZ_PASSWORD:root}
              provider: hikaricp
