services:

  loki:
    container_name: loki
    image: grafana/loki:main
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail:main
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      # Mount host log dir into promtail log dir
      - user-service-log:/var/log/user-service
      - product-service-log:/var/log/product-service
      - order-service-log:/var/log/order-service
      - notification-service-log:/var/log/notification-service
      - discovery-server-log:/var/log/discovery-server
      - auth-server-log:/var/log/discovery-server
      - api-gateway-log:/var/log/api-gateway
    depends_on:
      - loki

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-config.yml:/etc/prometheus/prometheus-config.yml

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_DB=db_zipkin
      - MYSQL_USER=root
      - MYSQL_PASS=root

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
