version: "3"

services:

  discovery-server:
    container_name: discovery-server
    image: discovery-server:latest
    build:
      context: ../../../edge/discovery-server/discovery-server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 256M
    ports:
      - "8761:8761"
    volumes:
      - discovery-server-log:/var/log/discovery-server # Mount container log dir into host log dir

  user-service:
    container_name: user-service
    image: user-service:latest
    build:
      context: ../../../application/spring-boot/user-application
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    ports:
      - "8081:8081"
    environment:
      - EUREKA_DEFAULT_ZONE=http://discovery-server:8761/eureka
      - MYSQL_URL=jdbc:mysql://mysql:3306/db_user?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    volumes:
      - user-service-log:/var/log/user-service
    depends_on:
      - discovery-server

  product-service:
    container_name: product-service
    image: product-service:latest
    build:
      context: ../../../application/spring-boot/product-application
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    ports:
      - "8082:8082"
    environment:
      - EUREKA_DEFAULT_ZONE=http://discovery-server:8761/eureka
      - MYSQL_URL=jdbc:mysql://mysql:3306/db_product?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    volumes:
      - product-service-log:/var/log/product-service
    depends_on:
      - discovery-server

  order-service:
    container_name: order-service
    image: order-service:latest
    build:
      context: ../../../application/spring-boot/order-application
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    ports:
      - "8083:8083"
    environment:
      - EUREKA_DEFAULT_ZONE=http://discovery-server:8761/eureka
      - GRPC_CLIENT_USER_ADDRESS=static://user-service:50051
      - GRPC_CLIENT_PRODUCT_ADDRESS=static://product-service:50052
      - REST_USER_BASE_URL=http://user-service:8081
      - REST_PRODUCT_BASE_URL=http://product-service:8082
      - MYSQL_URL=jdbc:mysql://mysql:3306/db_order?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    volumes:
      - order-service-log:/var/log/order-service
    depends_on:
      - discovery-server

  notification-service:
    container_name: notification-service
    image: notification-service:latest
    build:
      context: ../../../application/spring-boot/notification-service
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    ports:
      - "8084:8084"
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/db_notification?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - MAIL_SERVER_HOST=smtp4dev
    volumes:
      - notification-service-log:/var/log/notification-service

  auth-server:
    container_name: auth-server
    image: auth-server:latest
    build:
      context: ../../../edge/auth-server/auth-server-spring-security-jwt
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    ports:
      - "8091:8091"
    environment:
      - EUREKA_DEFAULT_ZONE=http://discovery-server:8761/eureka
      - MYSQL_URL=jdbc:mysql://mysql:3306/db_auth?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - auth-server-log:/var/log/auth-server
    depends_on:
      - discovery-server

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      context: ../../../edge/api-gateway/api-gateway-spring-cloud-gateway
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 256M
    ports:
      - "8080:8080"
    environment:
      - EUREKA_DEFAULT_ZONE=http://discovery-server:8761/eureka
      - JWK_SET_URI=http://auth-server:8091/.well-known/jwks.json
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    volumes:
      - api-gateway-log:/var/log/api-gateway
    depends_on:
      - discovery-server

volumes:
  discovery-server-log:
  user-service-log:
  product-service-log:
  order-service-log:
  notification-service-log:
  auth-server-log:
  api-gateway-log:
