// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.1
package org.atlas.platform.grpc.protobuf.user;

public final class User {

  private User() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_user_ListUserRequestProto_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_ListUserRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_user_UserProto_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_user_UserListProto_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserListProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\n\nuser.proto\022\004user\032\033google/protobuf/empt" +
            "y.proto\"\'\n\024ListUserRequestProto\022\017\n\007user_" +
            "id\030\001 \003(\005\"c\n\tUserProto\022\n\n\002id\030\001 \001(\005\022\r\n\005ema" +
            "il\030\002 \001(\t\022\022\n\nfirst_name\030\003 \001(\t\022\021\n\tlast_nam" +
            "e\030\004 \001(\t\022\024\n\014phone_number\030\005 \001(\t\".\n\rUserLis" +
            "tProto\022\035\n\004user\030\001 \003(\0132\017.user.UserProto2L\n" +
            "\013UserService\022=\n\010ListUser\022\032.user.ListUser" +
            "RequestProto\032\023.user.UserListProto\"\000B)\n%o" +
            "rg.atlas.platform.grpc.protobuf.userP\001b\006" +
            "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
                com.google.protobuf.EmptyProto.getDescriptor(),
            });
    internal_static_user_ListUserRequestProto_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_user_ListUserRequestProto_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_ListUserRequestProto_descriptor,
        new java.lang.String[]{"UserId",});
    internal_static_user_UserProto_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_user_UserProto_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserProto_descriptor,
        new java.lang.String[]{"Id", "Email", "FirstName", "LastName", "PhoneNumber",});
    internal_static_user_UserListProto_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_user_UserListProto_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserListProto_descriptor,
        new java.lang.String[]{"User",});
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
