// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

// Protobuf Java Version: 3.25.1
package org.atlas.platform.grpc.protobuf.user;

public interface UserListProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserListProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .user.UserProto user = 1;</code>
   */
  java.util.List<org.atlas.platform.grpc.protobuf.user.UserProto>
  getUserList();

  /**
   * <code>repeated .user.UserProto user = 1;</code>
   */
  org.atlas.platform.grpc.protobuf.user.UserProto getUser(int index);

  /**
   * <code>repeated .user.UserProto user = 1;</code>
   */
  int getUserCount();

  /**
   * <code>repeated .user.UserProto user = 1;</code>
   */
  java.util.List<? extends org.atlas.platform.grpc.protobuf.user.UserProtoOrBuilder>
  getUserOrBuilderList();

  /**
   * <code>repeated .user.UserProto user = 1;</code>
   */
  org.atlas.platform.grpc.protobuf.user.UserProtoOrBuilder getUserOrBuilder(
      int index);
}
