app:
  config:
    default:
      system:
        locale: en-US
        cors:
          allowed-origins:
            - http://localhost:9000
            - http://localhost:9100
          allowed-methods:
            - "GET"
            - "POST"
            - "PUT"
            - "PATCH"
            - "DELETE"
            - "OPTIONS"
          allowed-headers:
            - "*"
          allow-credentials: true
          max-age: 0 # always fetch the latest data
      product-service:
        product-cache-name: product
        product-import-bucket: product
        decrease-quantity-strategy: DISTRIBUTED_LOCK
      notification-service:
        email:
          sender: admin@atlas.org
