app:
  config:
    default:
      system:
        locale: en-US
        cors.allowed-origins:
          - http://localhost:9000 # local storefront app
          - http://localhost:9100 # local admin app
        cors.allowed-methods:
          - "GET"
          - "POST"
          - "PUT"
          - "PATCH"
          - "DELETE"
          - "OPTIONS"
        cors.allowed-headers:
          - "*"
        cors.allow-credentials: true
        cors.max-age: 3600
      product-service:
        product-cache-name: product
        product-import-bucket: product
        decrease-quantity-strategy: DISTRIBUTED_LOCK
      notification-service:
        email.sender: admin@atlas.org
