spring:
  kafka:
    consumer:
      group-id: ${spring.application.name}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  event:
    kafka:
      topic:
        user-registered-event: user-registered-event
        product-created-event: product-created-event
        product-updated-event: product-updated-event
        product-deleted-event: product-deleted-event
        order-created-event: order-created-event
        reserve-quantity-succeeded-event: reserve-quantity-succeeded-event
        reserve-quantity-failed-event: reserve-quantity-failed-event
        order-confirmed-event: order-confirmed-event
        order-canceled-event: order-canceled-event
