spring:
  kafka:
    consumer:
      group-id: ${spring.application.name}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  event:
    kafka:
      topic:
        user-events: user-events
        product-events: product-events
        order-events: order-events
