grpc:
  server:
    port: 50052
    security:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true # Enable liveness and readiness probe endpoints
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8082

spring:
  application:
    name: product-service
  profiles:
    active: local-compose
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_product?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        # Enable batch inserts
        jdbc:
          batch_size: 50
        order_inserts: true
    show-sql: true

springdoc:
  packages-to-scan: org.atlas.platform.rest.server.product.controller
