app:
  event:
    sns:
      sns-topic-arn:
        user-events: ${SNS_TOPIC_ARN_USER_EVENTS}
        product-events: ${SNS_TOPIC_ARN_PRODUCT_EVENTS}
        order-events: ${SNS_TOPIC_ARN_ORDER_EVENTS}
      sqs-queue-url:
        user-events: ${SQS_QUEUE_URL_USER_EVENTS}
        product-events: ${SQS_QUEUE_URL_PRODUCT_EVENTS}
        order-events: ${SQS_QUEUE_URL_ORDER_EVENTS}
      visibility-timeout: 30
      wait-time-seconds: 20
      batch-size: 10
