management:
  endpoint:
    health:
      probes:
        enabled: true # Enable liveness and readiness probe endpoints
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  port: 8080

spring:
  application:
    name: gateway-server
  profiles:
    active: local-compose
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**,/api/categories/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

app:
  gateway:
    authorization-rules:
      non-secured-paths:
        - "/api/users/sign-up"
        - "/api/users/sign-in"
        - "/actuator/**"
      secured-paths:
        - path: "/api/users/profile"
          roles: [ "CUSTOMER" ]
        - path: "/api/users/sign-out"
          roles: [ "CUSTOMER" ]
        - path: "/api/products/search"
          roles: [ "CUSTOMER" ]
        - path: "/api/categories"
          roles: [ "CUSTOMER" ]
        - path: "/api/orders/**"
          roles: [ "CUSTOMER" ]
        - path: "/api/reports"
          roles: [ "ADMIN" ]
