spring:
  cloud:
    gateway:
      # We will configure Service Connect for ECS services. And uri is service DNS.
      routes:
        - id: user-service
          uri: ${USER_SERVICE_DNS:http://user-service:8081}
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: ${PRODUCT_SERVICE_DNS:http://product-service:8082}
          predicates:
            - Path=/api/products/**,/api/categories/**
        - id: order-service
          uri: ${ORDER_SERVICE_DNS:http://order-service:8083}
          predicates:
            - Path=/api/orders/**
        - id: report-service
          uri: ${REPORT_SERVICE_DNS:http://report-service:8085}
          predicates:
            - Path=/api/reports/**
      discovery:
        locator:
          enabled: false
