spring:
  cloud:
    gateway:
      # We will configure Service Connect for ECS services. And uri is service DNS.
      routes:
        # User Service Routes
        - id: user-service-auth
          uri: ${USER_SERVICE_DNS:http://user-service:8081}
          predicates:
            - Path=/api/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: user-service-admin
          uri: ${USER_SERVICE_DNS:http://user-service:8081}
          predicates:
            - Path=/api/admin/users/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: user-service-front
          uri: ${USER_SERVICE_DNS:http://user-service:8081}
          predicates:
            - Path=/api/front/users/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: user-service-api-docs
          uri: ${USER_SERVICE_DNS:http://user-service:8081}
          predicates:
            - Path=/api-docs/user-service
          filters:
            - RewritePath=/api-docs/user-service, /api-docs
        # Product Service Routes
        - id: product-service-admin
          uri: ${PRODUCT_SERVICE_DNS:http://user-service:8082}
          predicates:
            - Path=/api/admin/products/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: product-service-front
          uri: ${PRODUCT_SERVICE_DNS:http://user-service:8082}
          predicates:
            - Path=/api/front/products/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: product-service-master
          uri: ${PRODUCT_SERVICE_DNS:http://user-service:8082}
          predicates:
            - Path=/api/master/brands/**,/api/master/categories/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: product-service-api-docs
          uri: ${PRODUCT_SERVICE_DNS:http://user-service:8082}
          predicates:
            - Path=/api-docs/product-service
          filters:
            - RewritePath=/api-docs/product-service, /api-docs
        # Order Service Routes
        - id: order-service-admin
          uri: ${ORDER_SERVICE_DNS:http://user-service:8083}
          predicates:
            - Path=/api/admin/orders/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: order-service-front
          uri: ${ORDER_SERVICE_DNS:http://user-service:8083}
          predicates:
            - Path=/api/front/orders/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: order-service-api-docs
          uri: ${ORDER_SERVICE_DNS:http://user-service:8083}
          predicates:
            - Path=/api-docs/order-service
          filters:
            - RewritePath=/api-docs/order-service, /api-docs
      discovery:
        locator:
          enabled: false
