server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User service
        - id: user-service-common
          uri: lb://user-service
          predicates:
            - Path=/api/common/users/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SessionValidation
            - TokenRelay
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/api/admin/users/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SessionValidation
            - TokenRelay
        - id: user-service-front
          uri: lb://user-service
          predicates:
            - Path=/api/front/users/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SessionValidation
            - TokenRelay
        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/api-docs/user-service
          filters:
            - RewritePath=/api-docs/user-service, /api-docs
        # Auth service
        - id: auth-server-auth
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: auth-server-api-docs
          uri: lb://auth-server
          predicates:
            - Path=/api-docs/auth-server
          filters:
            - RewritePath=/api-docs/auth-server, /api-docs
        # Product service
        - id: product-service-admin
          uri: lb://product-service
          predicates:
            - Path=/api/admin/products/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SessionValidation
            - TokenRelay
        - id: product-service-front
          uri: lb://product-service
          predicates:
            - Path=/api/front/products/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SessionValidation
            - TokenRelay
        - id: product-service-common
          uri: lb://product-service
          predicates:
            - Path=/api/common/products/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SessionValidation
            - TokenRelay
        - id: product-service-api-docs
          uri: lb://product-service
          predicates:
            - Path=/api-docs/product-service
          filters:
            - RewritePath=/api-docs/product-service, /api-docs
        # Order service
        - id: order-service-admin
          uri: lb://order-service
          predicates:
            - Path=/api/admin/orders/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SessionValidation
            - TokenRelay
        - id: order-service-front
          uri: lb://order-service
          predicates:
            - Path=/api/front/orders/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SessionValidation
            - TokenRelay
        - id: order-service-api-docs
          uri: lb://order-service
          predicates:
            - Path=/api-docs/order-service
          filters:
            - RewritePath=/api-docs/order-service, /api-docs
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  reactor:
    context-propagation: auto # Enable tracing
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8091/.well-known/jwks.json}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /api-docs/user-service
      - name: Product Service
        url: /api-docs/product-service
      - name: Order Service
        url: /api-docs/order-service
      - name: Auth Server
        url: /api-docs/auth-server
    default-models-expand-depth: -1 # Hide Schemas section

app:
  api-gateway:
    auth-rules:
      non-secured-paths:
        - "/actuator/**"
        - "/api/auth/login"
        - "/api/auth/logout"
        - "/api/auth/ott/generate"
        - "/api/auth/ott/login"
        - "/api/front/users/register"
        - "/api-docs/**"
        - "/swagger-ui/**"
      secured-paths:
        - path: "/api/common/**"
          roles: [ "USER", "ADMIN" ]
        - path: "/api/front/**"
          roles: [ "USER" ]
        - path: "/api/admin/**"
          roles: [ "ADMIN" ]
