server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # User Service Routes
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/api/admin/users/**
        - id: user-service-front
          uri: lb://user-service
          predicates:
            - Path=/api/front/users/**
        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/api-docs/user-service
          filters:
            - RewritePath=/api-docs/user-service, /api-docs
        # Product Service Routes
        - id: product-service-admin
          uri: lb://product-service
          predicates:
            - Path=/api/admin/products/**
        - id: product-service-front
          uri: lb://product-service
          predicates:
            - Path=/api/front/products/**
        - id: product-service-master
          uri: lb://product-service
          predicates:
            - Path=/api/master/brands/**,/api/master/categories/**
        - id: product-service-api-docs
          uri: lb://product-service
          predicates:
            - Path=/api-docs/product-service
          filters:
            - RewritePath=/api-docs/product-service, /api-docs
        # Order Service Routes
        - id: order-service-admin
          uri: lb://order-service
          predicates:
            - Path=/api/admin/orders/**
        - id: order-service-front
          uri: lb://order-service
          predicates:
            - Path=/api/front/orders/**
        - id: order-service-api-docs
          uri: lb://order-service
          predicates:
            - Path=/api-docs/order-service
          filters:
            - RewritePath=/api-docs/order-service, /api-docs
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /api-docs/user-service
      - name: Product Service
        url: /api-docs/product-service
      - name: Order Service
        url: /api-docs/order-service

app:
  gateway:
    authorization-rules:
      non-secured-paths:
        - "/api/gateway/**"
        - "/actuator/**"
        - "/api/auth/login"
        - "/api/auth/logout"
        - "/api/front/users/register"
        - "/api-docs/**"
      secured-paths:
        - path: "/api/master/**"
          roles: [ "USER", "ADMIN" ]
        - path: "/api/front/**"
          roles: [ "USER" ]
        - path: "/api/admin/**"
          roles: [ "ADMIN" ]
