server:
  port: 8080

spring:
  application:
    name: gateway-server
  profiles:
    active: local-compose
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/front/users/$\{segment}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**,/api/categories/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

app:
  gateway:
    authorization-rules:
      non-secured-paths:
        - "/api/gateway/**"
        - "/actuator/**"
        - "/api/users/login"
        - "/api/users/register"
      secured-paths:
        - path: "/api/users/profile"
          roles: [ "USER", "ADMIN" ]
        - path: "/api/products/search"
          roles: [ "USER" ]
        - path: "/api/categories"
          roles: [ "USER" ]
        - path: "/api/orders/**"
          roles: [ "USER" ]
        - path: "/api/admin/*"
          roles: [ "ADMIN" ]
