server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # User Service Routes
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/api/admin/users/**
        - id: user-service-front
          uri: lb://user-service
          predicates:
            - Path=/api/front/users/**
        # Product Service Routes
        - id: product-service-admin
          uri: lb://product-service
          predicates:
            - Path=/api/admin/products/**
        - id: product-service-front
          uri: lb://product-service
          predicates:
            - Path=/api/front/products/**
        - id: product-service-master
          uri: lb://product-service
          predicates:
            - Path=/api/master/brands/**,/api/master/categories/**
        # Order Service Routes
        - id: order-service-admin
          uri: lb://order-service
          predicates:
            - Path=/api/admin/orders/**
        - id: order-service-front
          uri: lb://order-service
          predicates:
            - Path=/api/front/orders/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
app:
  gateway:
    authorization-rules:
      non-secured-paths:
        - "/api/gateway/**"
        - "/actuator/**"
        - "/api/auth/login"
        - "/api/auth/logout"
        - "/api/front/users/register"
      secured-paths:
        - path: "/api/master/**"
          roles: [ "USER", "ADMIN" ]
        - path: "/api/front/**"
          roles: [ "USER" ]
        - path: "/api/admin/**"
          roles: [ "ADMIN" ]
