spring:
  datasource:
    order:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_order?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:root}
    product:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_product?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:root}
    user:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_user?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      # This will ensure that only script-based schema generation is performed using schema.sql.
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        # Enable batch inserts
        jdbc:
          batch_size: 50
        order_inserts: true
    show-sql: true
