grpc:
  client:
    catalog-service:
      enableKeepAlive: 'true'
      negotiationType: plaintext
      keepAliveWithoutCalls: 'true'
      address: ${API_CLIENT_GRPC_CATALOG_SERVICE_ADDRESS:'static://127.0.0.1:50052'}
