spring:
  cloud:
    gateway:
      # We will configure Service Connect for ECS services. And uri is service DNS.
      routes:
        - id: product-service
          uri: ${PRODUCT_SERVICE_DNS:http://product-service:8081}
          predicates:
            - Path=/api/products/**,/api/categories/**
        - id: order-service
          uri: ${ORDER_SERVICE_DNS:http://order-service:8082}
          predicates:
            - Path=/api/orders/**
        - id: aggregator-service
          uri: ${AGGREGATOR_SERVICE_DNS:http://aggregator-service:8083}
          predicates:
            - Path=/api/aggregators/**
      discovery:
        locator:
          enabled: false
