spring:
  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES:}
      password: ${REDIS_PASSWORD:123456}
      ssl:
        enabled: true

app:
  event:
    sns:
      order-topic-arn: ${ORDER_TOPIC_ARN}
      order-queue-url: ${ORDER_QUEUE_URL}
      batch-size: 10
      wait-time-seconds: 20
      visibility-timeout: 30
