spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  event:
    rabbitmq:
      order-exchange: order_events
      order-queue: order_events.<service_name>
