logging:
  level:
    # Log core scheduler events
    org.quartz.core: DEBUG

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          dataSource:
            quartz:
              driver: com.mysql.cj.jdbc.Driver
              URL: ${MYSQL_QUARTZ_URL:jdbc:mysql://localhost:3306/db_quartz?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
              user: ${MYSQL_QUARTZ_USERNAME:root}
              password: ${MYSQL_QUARTZ_PASSWORD:root}
              provider: hikaricp
          scheduler:
            instanceId: AUTO
            instanceName: DefaultScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: quartz
            tablePrefix: QRTZ_
            isClustered: true
          threadPool:
            threadCount: 10
